x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
    - WEBHOOK_URL='https://n8n.storage24.com/'
    - NODE_OPTIONS="--max-old-space-size=8192"
    - N8N_LOG_OUTPUT=console
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - EXECUTIONS_DATA_PRUNE=true
    - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
  links:
    - postgres
    - redis
  volumes:
    - /etc/n8n_storage:/home/node/.n8n
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - /etc/db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    volumes:
      - /etc/redis_storage:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    container_name: n8n
    ports:
      - 5678:5678

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n
    deploy:
      replicas: 6

  n8n-webhook-1:
    <<: *shared
    command: webhook
    ports:
      - "5681:5678"
    depends_on:
      - n8n
    container_name: n8n-webhook-1

  n8n-webhook-2:
    <<: *shared
    command: webhook
    ports:
      - "5682:5678"
    depends_on:
      - n8n
    container_name: n8n-webhook-2

  n8n-webhook-3:
    <<: *shared
    command: webhook
    ports:
      - "5683:5678"
    depends_on:
      - n8n
    container_name: n8n-webhook-3
